# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b0d17fff900379ee338cf76d10c1e11756607f4da6f0d254980270c50eaf1f5731388a7247284e8db752229b4b9acadd4af47d45e3efd6862a3d88b35f9f415

test:
  secret_key_base: e29938034a01de328dd134291ffcc30daba78bfdf952e997b8a793c7d599c547cff6c862d479887963adb53fb241157596d6bdfbe4beddb864cd699ee738f904

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
